### ISSUE TITLE
有没有apollo-mi分支的自动构建？

### ISSUE THREAD

**Issue by h88782481** [CHIZI-0618/RK-KernelSU_Action#1]
如题

**Comment by CHIZI-0618** [comment]
fork 后进入 Actions 点击左侧 Build Kernel，再点击右侧的 Run workflow
![image](https://user-images.githubusercontent.com/51962278/218688663-cb55cef1-2165-4a9d-b6e6-c245fb009d49.png)
分支可改，填 apollo-mi 即可。
据我测试这个内核 kprobe 是不行的，所以用的手动修改源码，项目里的 KernelSU.patch 我是根据 munch-mi 分支写的，其他分支我没有测试。


记得修改 Clang URL 链接，原 release 已删除，最新的是 https://github.com/ZyCromerZ/Clang/releases/download/17.0.0-20230214-release/Clang-17.0.0-20230214.tar.gz

**Comment by CHIZI-0618** [comment]
![image](https://user-images.githubusercontent.com/51962278/218688663-cb55cef1-2165-4a9d-b6e6-c245fb009d49.png)
分支可改，填 apollo-mi 即可。

**Comment by CHIZI-0618** [comment]
defconfig 也要改，看起来应该是 apollo_defconfig，与 munch 不同，它不在 vendor 目录
@h88782481

**Comment by h88782481** [comment]
> 

好的，我去尝试一下

**Comment by h88782481** [comment]
![image](https://user-images.githubusercontent.com/54714341/218695500-7e3204dd-fc70-4777-ac72-d9c70269cc89.png)
并没有成功构建

**Comment by CHIZI-0618** [comment]
> ![image](https://user-images.githubusercontent.com/54714341/218695500-7e3204dd-fc70-4777-ac72-d9c70269cc89.png) 并没有成功构建

你还是填错了，Defconfig 那一栏只写 `apollo_defconfig`，不要瞎造

![image](https://user-images.githubusercontent.com/51962278/218696473-38a032d3-551e-498e-9181-e6e162cd947f.png)
