### ISSUE TITLE
请问能不能集成ksu最新的救砖方法

### ISSUE THREAD

**Issue by h88782481** [CHIZI-0618/RK-KernelSU_Action#3]
![image](https://user-images.githubusercontent.com/54714341/219273933-23f886c3-af4d-46c0-978d-dcdd0b609bb6.png)

**Comment by h88782481** [comment]
![image](https://user-images.githubusercontent.com/54714341/219276148-21d62091-388b-4830-b87d-1f8c51ae8dc9.png)

**Comment by CHIZI-0618** [comment]
c7e99b3c033af7169e4b7b1d07105c9f5a30daeb

**Comment by CHIZI-0618** [comment]
https://github.com/CHIZI-0618/RK-KernelSU_Action/actions/runs/4191510802

**Comment by h88782481** [comment]
好的感谢
